app/user_manager/forms.py
#---FORMULARIOS PARA LA BLUEPRINT ADMIN
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
#from app.user_manager import models


#---formulario para inicio de sesion con Amdin
class LoginAdminFormulario(FlaskForm):
    usuario = StringField("Usuario", validators=[DataRequired()])
    contrasena = PasswordField("Contraseña", validators=[DataRequired()])
    submit = SubmitField("Entrar")

#---FORMULARIO PARA CAMBIO SE CONTRASEÑA
class CambiarContraseñaAdminForm(FlaskForm):
    contrasena_actual = PasswordField("Contraseña Actual", validators=[DataRequired()])
    contrasena_nueva = PasswordField("Nueva Contraseña", validators=[DataRequired()])
    contrasena_confirmacion = PasswordField("Confirme Nueva Contraseña", validators=[DataRequired()])
    submit = SubmitField("Cambiar contraseña")

#---BARRA DE BUSQUEDA DE USUARIOS
class BarraBusquedaUsuarios(FlaskForm):
    usuario_buscar = StringField(validators=[DataRequired()])
    submit = SubmitField("Buscar")

app/user_manager/__init__.py
#-------INICIALIZADOR DEL BLUPRINT USER_MANAGER
from flask import Blueprint

#---creacion del blueprint indicando su nombre y carpeta templates
user_manager = Blueprint("user_manager", __name__, template_folder="templates")

#---indicar sus rutas
from app.user_manager import views

app/user_manager/views.py
#-------RUTAS DE BLUEPRINT USER_MANAGER
from flask import Flask, render_template, flash, redirect, url_for
from app.user_manager import user_manager
from app.user_manager.forms import LoginAdminFormulario, CambiarContraseñaAdminForm, BarraBusquedaUsuarios
from flask_login import current_user, login_user, login_required, logout_user
from app.usuario.models import Usuario
from app import database, bcrypt


#metodo para saber si eres admin o no
def es_admin(usuario):
    if usuario.rol != "Admin":
        return False
    else:
        return True

#---rutas de user_manager
@user_manager.route("/", methods=['GET', 'POST'])
def index():

    formulario = LoginAdminFormulario()

    
    #si ya estas en admin
    if current_user.is_authenticated:
        flash("YA ESTAS EN CUENTA")
        return redirect(url_for('usuario.home'))
    

    #si el formulario fue valido 
    if formulario.validate_on_submit():

        admi = Usuario.query.filter_by(rol="Admin").first()

        if admi and admi.checar_contrasena(formulario.contrasena.data):
            login_user(admi)
            flash("Incio de sesion admin exitoso", 'success')
            return redirect(url_for('user_manager.dashboard_admin'))
    
        else:
            flash("Credenciales incorrectas intente de nuevo", 'danger')
            return redirect(url_for('user_manager.index'))
    

    context = {
        'formulario':formulario
    }
    

    return render_template("index_admin.html", **context)


#---vista dashboard admin
@user_manager.route('/dashboard')
@login_required
def dashboard_admin():

    if es_admin(current_user) == False:
        redirect(url_for("user_manager.index"))

    admin = current_user

    #sacar informacion de la base de datos

    #total de una tabla
    total_usuarios = Usuario.query.count()

    #total de usuarios no aprobados
    usuarios_no_aprobados = Usuario.query.filter_by(status=0).count()

    #totoal de usuarios aprobados
    usuarios_aprobados = Usuario.query.filter_by(status=1).count()

    context = {
        'nombre':admin.usuario_nombres,
        'total_usuarios':total_usuarios,
        'usuarios_no_aprobados':usuarios_no_aprobados,
        'usuarios_aprobados':usuarios_aprobados
    }

    return render_template('dashboard_admin.html', **context)


#---vista logout
@user_manager.route('/logout')
def logout_admin():
    logout_user()
    return redirect(url_for('user_manager.index'))



#---vista para ver todos los usuarios
@user_manager.route('/ver_usuarios', methods=['POST', 'GET'])
@login_required
def ver_usuarios():

    if es_admin(current_user) == False:
        return redirect(url_for('user_manager.index'))

    
    barra = BarraBusquedaUsuarios()

    #validacion para saber si se uso o no los usuarios
    if barra.validate_on_submit():
        usuario_buscar = barra.usuario_buscar.data
        usuarios = Usuario.query.filter(Usuario.usuario_nombres.like(f"%{usuario_buscar}%")).all()
        context={'usuarios':usuarios,
                 'barra':barra}
        return render_template("ver_usuario.html", **context)


    #sacamos todos los usuarios en forma de lista
    usuarios = Usuario.query.all()

    context = {
        'usuarios':usuarios,
        'barra':barra
    }


    return render_template("ver_usuario.html", **context)


#---vista para aprobar usuarios, se le pasa el id en la url
@user_manager.route('/aprobar_usuario/<int:id>')
@login_required
def aprobar_usuario(id):

    #se filtra el usuario
    usuario_actualizar = Usuario.query.filter_by(id=id).first()

    #si existe el usuario
    if usuario_actualizar:
        # se cambia su atributo status de 0 a 1
        usuario_actualizar.status = 1

        flash(f"El usuario con el id:{id} se ha aprovado con exito")
    
        #se aplica los cambios a la base de datos
        database.session.commit()


    return redirect(url_for('user_manager.ver_usuarios'))

#---vista para cambiar contraseña usuairo
@user_manager.route('/cambiar_contrasena_admin', methods=['POST', 'GET'])
@login_required
def cambiar_contrasena_admin():

    #checa si es admin
    if es_admin(current_user) == False:
        return redirect(url_for('usuario.login_usaurio'))
    
    formulario = CambiarContraseñaAdminForm()


    if formulario.validate_on_submit():
        admin = Usuario.query.filter_by(rol='Admin', id=current_user.id).first()

        if admin and admin.checar_contrasena(formulario.contrasena_actual.data):
            admin.usuario_contrasena = bcrypt.generate_password_hash(formulario.contrasena_nueva.data).decode('utf-8')
            database.session.commit()

            flash("Se cambio la contraseña correctamente", 'success')
            return redirect(url_for('user_manager.dashboard_admin'))

        else:
            flash("Contraseña actual no correcta", 'danger')
            return redirect(url_for('user_manager.cambiar_contrasena_admin'))


    context = {
        'formulario':formulario
    }

    return render_template("cambio_contrasena_admin.html", **context)

app/user_manager/templates/base_admin.html
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <!--BOOTSTRAP-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    
    <title>
        {% block titulo %}
        
        {% endblock titulo %}
    </title>



    {% block head %}

    {% endblock head %}

</head>




<body>

        <!--Ver los mensajes que tienen-->
        {% with mensajes = get_flashed_messages(with_categories=True) %}
        {% if mensajes %}
            <div class="container">
                {% for categoria, mensaje in mensajes %}
                    <div class="alert alert-{{ categoria }} alert-dismissible fade show" role="alert">
                        {{ mensaje }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}


    {% block contenido %}
    
    {% endblock contenido %}
</body>


</html>

app/user_manager/templates/cambio_contrasena_admin.html
{% extends 'base_admin.html' %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block titulo %}
    Cambio Contraseña Admin
{% endblock %}


{% block contenido %}

<div class="d-flex justify-content-center">
    <h3>Cambio Contraseña Admin</h3>
</div>

<div class="container">
    {{ formulario.hidden_tag() }}
    {{ wtf.quick_form(formulario) }}
</div>

{% endblock %}

app/user_manager/templates/dashboard_admin.html
{% extends 'base_admin.html' %}

{% block titulo %} DASHBOARD ADMIN {% endblock %}


{% block contenido %}
<div class="d-flex justify-content-center">
    <h3>BIENVENIDO {{nombre}}</h3>
</div>

<br>

<dic class="row d-flex justify-content-center">
    <div class="col-xl-3 col-lg-3 col-md-3 my-2 col-sm-12">
        <a href="" class="btn btn-info w-full">DASHBOARD</a>
    </div>

    <div class="col-xl-3 col-lg-3 col-md-3 my-2 col-sm-12">
        <a href="{{url_for('user_manager.cambiar_contrasena_admin')}}" class="btn btn-info w-full">Cambiar contraseña ADMIN</a>
    </div>


    <div class="col-xl-3 col-lg-3 col-md-3 my-2 col-sm-12">
        <a href="{{url_for('user_manager.ver_usuarios')}}" class="btn btn-info w-full">Ver usuarios</a>
    </div>

    <div class="col-xl-3 col-lg-3 col-md-3 my-2 col-sm-12">
        <a href="{{url_for('user_manager.logout_admin')}}" class="btn btn-info w-full">SALIR</a>
    </div>


</dic>

<br>

<!--MOSTRAR INFORMACION A ADMIN CON CARTAS-->
<div class="container">
    <div class="row">

        <!--total usuarios-->
        <div class="col-xl-6 my-2 col-lg-6 col-sm-12">
            <div class="bg-success d-flex p-3 justify-content-between align-items-center">
                <h4>TOTAL USUARIOS</h4>
                <h5>{{total_usuarios}}</h5>
            </div>
        </div>

        <!--Usuarios aprobados-->
        <div class="col-xl-6 my-2 col-lg-6 col-sm-12">
            <div class="bg-warning d-flex p-3 justify-content-between align-items-center">
                <h4>USUARIOS APROBADOS</h4>
                <h5>{{usuarios_aprobados}}</h5>
            </div>
        </div>

        <!--Usuarios no aprobados-->
        <div class="col-xl-6 my-2 col-lg-6 col-sm-12">
            <div class="bg-danger d-flex p-3 justify-content-between align-items-center">
                <h4>USUARIOS NO APROBADOS</h4>
                <h5>{{usuarios_no_aprobados}}</h5>
            </div>
        </div>

    </div>
</div>


{% endblock %}

app/user_manager/templates/index_admin.html
{% extends 'base_admin.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block titulo %}
ADMIN INDEX
{% endblock %}

{% block contenido %}
<br>


<div class="container">
    <h3>INICIO DE SESION DE ADMINISTRADOR</h3>

    {{ formulario.hidden_tag() }}
    {{ wtf.quick_form(formulario) }}

</div>


{% endblock %}

app/user_manager/templates/ver_usuario.html
{% extends 'base_admin.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block titulo %}
    VER TODOS LOS USUARIOS
{% endblock %}

{% block contenido %}

<div class="d-flex justify-content-center">
    <h3>Lista de usuarios</h3>
</div>


<!--barra de busqueda-->
{{barra.hidden_tag()}}
{{wtf.quick_form(barra)}}



<!--TABLA PARA MOSTRAR LA INFORMACIONAS DE LOS USUARIOS-->
<div class="container">
    <div class="my-2">
        <div class="table-respoonsive">

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <!--columnas-->
                        <th>ID</th>
                        <th>R.P.E</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Correo</th>
                        <th>Fecha creación</th>
                        <th>Rol</th>
                        <th>STATUS</th>
                    </tr>
                </thead>

                <!--contenido de la tabla-->
                <tbody>

                    {% for usuario in usuarios %}

                    <tr>
                        <td>{{usuario.id}}</td>
                        <td>{{usuario.usuario_rpe}}</td>
                        <td>{{usuario.usuario_nombres}}</td>
                        <td>{{usuario.usuario_apellidos}}</td>
                        <td>{{usuario.usuario_email}}</td>
                        <td>{{usuario.usuario_creacion}}</td>
                        <td>{{usuario.rol}}</td>
                        <td>
                            {% if usuario.status == 0 %}
                               <a href="{{ url_for('user_manager.aprobar_usuario', id=usuario.id) }}">
                                <button class="btn btn-warning">¿APROBAR?</button>
                               </a>
                            {% else %}
                                APROBADO
                            {% endif %}
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
                

            </table>

        </div>
    </div>
</div>

{% endblock %}